// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentServer_AgentInfo_FullMethodName = "/proto.AgentServer/AgentInfo"
)

// AgentServerClient is the client API for AgentServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServerClient interface {
	AgentInfo(ctx context.Context, in *AgentInfoReq, opts ...grpc.CallOption) (*AgentInfoResp, error)
}

type agentServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServerClient(cc grpc.ClientConnInterface) AgentServerClient {
	return &agentServerClient{cc}
}

func (c *agentServerClient) AgentInfo(ctx context.Context, in *AgentInfoReq, opts ...grpc.CallOption) (*AgentInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfoResp)
	err := c.cc.Invoke(ctx, AgentServer_AgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServerServer is the server API for AgentServer service.
// All implementations must embed UnimplementedAgentServerServer
// for forward compatibility.
type AgentServerServer interface {
	AgentInfo(context.Context, *AgentInfoReq) (*AgentInfoResp, error)
	mustEmbedUnimplementedAgentServerServer()
}

// UnimplementedAgentServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServerServer struct{}

func (UnimplementedAgentServerServer) AgentInfo(context.Context, *AgentInfoReq) (*AgentInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentInfo not implemented")
}
func (UnimplementedAgentServerServer) mustEmbedUnimplementedAgentServerServer() {}
func (UnimplementedAgentServerServer) testEmbeddedByValue()                     {}

// UnsafeAgentServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServerServer will
// result in compilation errors.
type UnsafeAgentServerServer interface {
	mustEmbedUnimplementedAgentServerServer()
}

func RegisterAgentServerServer(s grpc.ServiceRegistrar, srv AgentServerServer) {
	// If the following call pancis, it indicates UnimplementedAgentServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentServer_ServiceDesc, srv)
}

func _AgentServer_AgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).AgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentServer_AgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).AgentInfo(ctx, req.(*AgentInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentServer_ServiceDesc is the grpc.ServiceDesc for AgentServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentServer",
	HandlerType: (*AgentServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgentInfo",
			Handler:    _AgentServer_AgentInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/agent.proto",
}
