// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: site/banner.proto

package site

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteBannerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category int32 `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"` // 类别(固定 1-热门 2-游戏 3-附近 4-推荐)
}

func (x *SiteBannerReq) Reset() {
	*x = SiteBannerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_banner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteBannerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteBannerReq) ProtoMessage() {}

func (x *SiteBannerReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_banner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteBannerReq.ProtoReflect.Descriptor instead.
func (*SiteBannerReq) Descriptor() ([]byte, []int) {
	return file_site_banner_proto_rawDescGZIP(), []int{0}
}

func (x *SiteBannerReq) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

// 系统站点配置响应
type SiteBannerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*SiteBannerResp_SiteBannerItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SiteBannerResp) Reset() {
	*x = SiteBannerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_banner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteBannerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteBannerResp) ProtoMessage() {}

func (x *SiteBannerResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_banner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteBannerResp.ProtoReflect.Descriptor instead.
func (*SiteBannerResp) Descriptor() ([]byte, []int) {
	return file_site_banner_proto_rawDescGZIP(), []int{1}
}

func (x *SiteBannerResp) GetList() []*SiteBannerResp_SiteBannerItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 启动图响应
type StartupImageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode  string `protobuf:"bytes,1,opt,name=countryCode,proto3" json:"countryCode,omitempty"`   // 国家编码
	LanguageCode string `protobuf:"bytes,2,opt,name=languageCode,proto3" json:"languageCode,omitempty"` // 语言编码
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                 // 启动图名称
	ImageUrl     string `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`         // 启动图URL地址
	ThumbnailUrl string `protobuf:"bytes,5,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"` // 启动图缩略图地址
}

func (x *StartupImageResp) Reset() {
	*x = StartupImageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_banner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartupImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupImageResp) ProtoMessage() {}

func (x *StartupImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_banner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupImageResp.ProtoReflect.Descriptor instead.
func (*StartupImageResp) Descriptor() ([]byte, []int) {
	return file_site_banner_proto_rawDescGZIP(), []int{2}
}

func (x *StartupImageResp) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *StartupImageResp) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *StartupImageResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartupImageResp) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *StartupImageResp) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type PageStayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageName string `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`  // 页面名称
	StayTime int32  `protobuf:"varint,2,opt,name=stayTime,proto3" json:"stayTime,omitempty"` // 停留时长 单位: 秒
}

func (x *PageStayReq) Reset() {
	*x = PageStayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_banner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageStayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageStayReq) ProtoMessage() {}

func (x *PageStayReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_banner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageStayReq.ProtoReflect.Descriptor instead.
func (*PageStayReq) Descriptor() ([]byte, []int) {
	return file_site_banner_proto_rawDescGZIP(), []int{3}
}

func (x *PageStayReq) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *PageStayReq) GetStayTime() int32 {
	if x != nil {
		return x.StayTime
	}
	return 0
}

type BannerClickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerType int32 `protobuf:"varint,1,opt,name=bannerType,proto3" json:"bannerType,omitempty"` // banner类型 1:首页banner 2:推荐banner 3:热门banner
}

func (x *BannerClickReq) Reset() {
	*x = BannerClickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_banner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerClickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerClickReq) ProtoMessage() {}

func (x *BannerClickReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_banner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerClickReq.ProtoReflect.Descriptor instead.
func (*BannerClickReq) Descriptor() ([]byte, []int) {
	return file_site_banner_proto_rawDescGZIP(), []int{4}
}

func (x *BannerClickReq) GetBannerType() int32 {
	if x != nil {
		return x.BannerType
	}
	return 0
}

type SiteBannerResp_SiteBannerItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri      string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`            // 图片地址
	ShowType int32  `protobuf:"varint,2,opt,name=showType,proto3" json:"showType,omitempty"` // 展示类型 1-纯展示 2-外链 3-直播间
	ExtInfo  string `protobuf:"bytes,3,opt,name=extInfo,proto3" json:"extInfo,omitempty"`    // 扩展信息 外链地址/直播间id
}

func (x *SiteBannerResp_SiteBannerItem) Reset() {
	*x = SiteBannerResp_SiteBannerItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_banner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteBannerResp_SiteBannerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteBannerResp_SiteBannerItem) ProtoMessage() {}

func (x *SiteBannerResp_SiteBannerItem) ProtoReflect() protoreflect.Message {
	mi := &file_site_banner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteBannerResp_SiteBannerItem.ProtoReflect.Descriptor instead.
func (*SiteBannerResp_SiteBannerItem) Descriptor() ([]byte, []int) {
	return file_site_banner_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SiteBannerResp_SiteBannerItem) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SiteBannerResp_SiteBannerItem) GetShowType() int32 {
	if x != nil {
		return x.ShowType
	}
	return 0
}

func (x *SiteBannerResp_SiteBannerItem) GetExtInfo() string {
	if x != nil {
		return x.ExtInfo
	}
	return ""
}

var File_site_banner_proto protoreflect.FileDescriptor

var file_site_banner_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x53, 0x69,
	0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xa4, 0x01, 0x0a, 0x0e, 0x53, 0x69, 0x74, 0x65,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x69, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x2e,
	0x53, 0x69, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x1a, 0x58, 0x0a, 0x0e, 0x53, 0x69, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x77,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x77,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xac,
	0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x45, 0x0a,
	0x0b, 0x50, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x61, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x41, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_banner_proto_rawDescOnce sync.Once
	file_site_banner_proto_rawDescData = file_site_banner_proto_rawDesc
)

func file_site_banner_proto_rawDescGZIP() []byte {
	file_site_banner_proto_rawDescOnce.Do(func() {
		file_site_banner_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_banner_proto_rawDescData)
	})
	return file_site_banner_proto_rawDescData
}

var file_site_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_site_banner_proto_goTypes = []any{
	(*SiteBannerReq)(nil),                 // 0: proto.SiteBannerReq
	(*SiteBannerResp)(nil),                // 1: proto.SiteBannerResp
	(*StartupImageResp)(nil),              // 2: proto.StartupImageResp
	(*PageStayReq)(nil),                   // 3: proto.PageStayReq
	(*BannerClickReq)(nil),                // 4: proto.BannerClickReq
	(*SiteBannerResp_SiteBannerItem)(nil), // 5: proto.SiteBannerResp.SiteBannerItem
}
var file_site_banner_proto_depIdxs = []int32{
	5, // 0: proto.SiteBannerResp.list:type_name -> proto.SiteBannerResp.SiteBannerItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_site_banner_proto_init() }
func file_site_banner_proto_init() {
	if File_site_banner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_site_banner_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SiteBannerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_banner_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SiteBannerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_banner_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StartupImageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_banner_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PageStayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_banner_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BannerClickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_banner_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SiteBannerResp_SiteBannerItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_banner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_site_banner_proto_goTypes,
		DependencyIndexes: file_site_banner_proto_depIdxs,
		MessageInfos:      file_site_banner_proto_msgTypes,
	}.Build()
	File_site_banner_proto = out.File
	file_site_banner_proto_rawDesc = nil
	file_site_banner_proto_goTypes = nil
	file_site_banner_proto_depIdxs = nil
}
