// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: site/config.proto

package site

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 系统站点配置响应
type SiteConfigsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceUri             string `protobuf:"bytes,1,opt,name=resourceUri,proto3" json:"resourceUri,omitempty"`                          // 资源地址
	DiamondExchangeUsdRatio int32  `protobuf:"varint,2,opt,name=diamondExchangeUsdRatio,proto3" json:"diamondExchangeUsdRatio,omitempty"` // 钻石兑换比列
	IsChangeBind            int32  `protobuf:"varint,3,opt,name=isChangeBind,proto3" json:"isChangeBind,omitempty"`                       // 是否开启换绑
}

func (x *SiteConfigsResp) Reset() {
	*x = SiteConfigsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteConfigsResp) ProtoMessage() {}

func (x *SiteConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteConfigsResp.ProtoReflect.Descriptor instead.
func (*SiteConfigsResp) Descriptor() ([]byte, []int) {
	return file_site_config_proto_rawDescGZIP(), []int{0}
}

func (x *SiteConfigsResp) GetResourceUri() string {
	if x != nil {
		return x.ResourceUri
	}
	return ""
}

func (x *SiteConfigsResp) GetDiamondExchangeUsdRatio() int32 {
	if x != nil {
		return x.DiamondExchangeUsdRatio
	}
	return 0
}

func (x *SiteConfigsResp) GetIsChangeBind() int32 {
	if x != nil {
		return x.IsChangeBind
	}
	return 0
}

var File_site_config_proto protoreflect.FileDescriptor

var file_site_config_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0f, 0x53,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x69,
	0x12, 0x38, 0x0a, 0x17, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x55, 0x73, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x17, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x55, 0x73, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x69, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x42, 0x1d,
	0x5a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_config_proto_rawDescOnce sync.Once
	file_site_config_proto_rawDescData = file_site_config_proto_rawDesc
)

func file_site_config_proto_rawDescGZIP() []byte {
	file_site_config_proto_rawDescOnce.Do(func() {
		file_site_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_config_proto_rawDescData)
	})
	return file_site_config_proto_rawDescData
}

var file_site_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_site_config_proto_goTypes = []any{
	(*SiteConfigsResp)(nil), // 0: proto.SiteConfigsResp
}
var file_site_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_site_config_proto_init() }
func file_site_config_proto_init() {
	if File_site_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_site_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SiteConfigsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_site_config_proto_goTypes,
		DependencyIndexes: file_site_config_proto_depIdxs,
		MessageInfos:      file_site_config_proto_msgTypes,
	}.Build()
	File_site_config_proto = out.File
	file_site_config_proto_rawDesc = nil
	file_site_config_proto_goTypes = nil
	file_site_config_proto_depIdxs = nil
}
