// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: site/follow.proto

package site

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 关注/取消关注请求
type FollowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowId int32 `protobuf:"varint,1,opt,name=followId,proto3" json:"followId,omitempty"` // 被关注用户
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowReq) GetFollowId() int32 {
	if x != nil {
		return x.FollowId
	}
	return 0
}

// 粉丝/关注列表请求
type FollowsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId   int32 `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *FollowsReq) Reset() {
	*x = FollowsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowsReq) ProtoMessage() {}

func (x *FollowsReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowsReq.ProtoReflect.Descriptor instead.
func (*FollowsReq) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowsReq) GetLastId() int32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *FollowsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FollowsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*FollowsItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FollowsResp) Reset() {
	*x = FollowsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowsResp) ProtoMessage() {}

func (x *FollowsResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowsResp.ProtoReflect.Descriptor instead.
func (*FollowsResp) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{2}
}

func (x *FollowsResp) GetList() []*FollowsItem {
	if x != nil {
		return x.List
	}
	return nil
}

type FollowsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Avatar   string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex      int32  `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	LevelId  int32  `protobuf:"varint,4,opt,name=levelId,proto3" json:"levelId,omitempty"`
	Sign     string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	Nickname string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *FollowsItem) Reset() {
	*x = FollowsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowsItem) ProtoMessage() {}

func (x *FollowsItem) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowsItem.ProtoReflect.Descriptor instead.
func (*FollowsItem) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{3}
}

func (x *FollowsItem) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowsItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FollowsItem) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *FollowsItem) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *FollowsItem) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *FollowsItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// 是否关注返回
type FollowCheckResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whether int32 `protobuf:"varint,1,opt,name=whether,proto3" json:"whether,omitempty"` // 是否关注
}

func (x *FollowCheckResp) Reset() {
	*x = FollowCheckResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCheckResp) ProtoMessage() {}

func (x *FollowCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCheckResp.ProtoReflect.Descriptor instead.
func (*FollowCheckResp) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{4}
}

func (x *FollowCheckResp) GetWhether() int32 {
	if x != nil {
		return x.Whether
	}
	return 0
}

// 获取粉丝/关注数量请求
type FollowCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *FollowCountReq) Reset() {
	*x = FollowCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCountReq) ProtoMessage() {}

func (x *FollowCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCountReq.ProtoReflect.Descriptor instead.
func (*FollowCountReq) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{5}
}

func (x *FollowCountReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FollowCountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowingCount int32 `protobuf:"varint,1,opt,name=followingCount,proto3" json:"followingCount,omitempty"` // 关注数量
	FansCount      int32 `protobuf:"varint,2,opt,name=fansCount,proto3" json:"fansCount,omitempty"`           // 粉丝数量
}

func (x *FollowCountResp) Reset() {
	*x = FollowCountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_follow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCountResp) ProtoMessage() {}

func (x *FollowCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_follow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCountResp.ProtoReflect.Descriptor instead.
func (*FollowCountResp) Descriptor() ([]byte, []int) {
	return file_site_follow_proto_rawDescGZIP(), []int{6}
}

func (x *FollowCountResp) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *FollowCountResp) GetFansCount() int32 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

var File_site_follow_proto protoreflect.FileDescriptor

var file_site_follow_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x09, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0a, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x35, 0x0a, 0x0b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x99, 0x01, 0x0a,
	0x0b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x77,
	0x68, 0x65, 0x74, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x68,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x0e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x57, 0x0a, 0x0f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x61,
	0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66,
	0x61, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x41, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_follow_proto_rawDescOnce sync.Once
	file_site_follow_proto_rawDescData = file_site_follow_proto_rawDesc
)

func file_site_follow_proto_rawDescGZIP() []byte {
	file_site_follow_proto_rawDescOnce.Do(func() {
		file_site_follow_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_follow_proto_rawDescData)
	})
	return file_site_follow_proto_rawDescData
}

var file_site_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_site_follow_proto_goTypes = []any{
	(*FollowReq)(nil),       // 0: proto.FollowReq
	(*FollowsReq)(nil),      // 1: proto.FollowsReq
	(*FollowsResp)(nil),     // 2: proto.FollowsResp
	(*FollowsItem)(nil),     // 3: proto.FollowsItem
	(*FollowCheckResp)(nil), // 4: proto.FollowCheckResp
	(*FollowCountReq)(nil),  // 5: proto.FollowCountReq
	(*FollowCountResp)(nil), // 6: proto.FollowCountResp
}
var file_site_follow_proto_depIdxs = []int32{
	3, // 0: proto.FollowsResp.list:type_name -> proto.FollowsItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_site_follow_proto_init() }
func file_site_follow_proto_init() {
	if File_site_follow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_site_follow_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FollowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_follow_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FollowsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_follow_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FollowsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_follow_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FollowsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_follow_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FollowCheckResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_follow_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FollowCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_follow_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FollowCountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_follow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_site_follow_proto_goTypes,
		DependencyIndexes: file_site_follow_proto_depIdxs,
		MessageInfos:      file_site_follow_proto_msgTypes,
	}.Build()
	File_site_follow_proto = out.File
	file_site_follow_proto_rawDesc = nil
	file_site_follow_proto_goTypes = nil
	file_site_follow_proto_depIdxs = nil
}
