// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: site/global_area.proto

package site

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalAreaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area []*GlobalAreaResp_GlobalArea `protobuf:"bytes,1,rep,name=area,proto3" json:"area,omitempty"`
	Lang []*GlobalAreaResp_GlobalLang `protobuf:"bytes,2,rep,name=lang,proto3" json:"lang,omitempty"`
}

func (x *GlobalAreaResp) Reset() {
	*x = GlobalAreaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_global_area_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalAreaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalAreaResp) ProtoMessage() {}

func (x *GlobalAreaResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_global_area_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalAreaResp.ProtoReflect.Descriptor instead.
func (*GlobalAreaResp) Descriptor() ([]byte, []int) {
	return file_site_global_area_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalAreaResp) GetArea() []*GlobalAreaResp_GlobalArea {
	if x != nil {
		return x.Area
	}
	return nil
}

func (x *GlobalAreaResp) GetLang() []*GlobalAreaResp_GlobalLang {
	if x != nil {
		return x.Lang
	}
	return nil
}

type GlobalAreaResp_GlobalArea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 国家名称
	MobileCode  string `protobuf:"bytes,2,opt,name=mobileCode,proto3" json:"mobileCode,omitempty"`   //手机代码
	CountryCode string `protobuf:"bytes,3,opt,name=countryCode,proto3" json:"countryCode,omitempty"` //国家码
}

func (x *GlobalAreaResp_GlobalArea) Reset() {
	*x = GlobalAreaResp_GlobalArea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_global_area_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalAreaResp_GlobalArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalAreaResp_GlobalArea) ProtoMessage() {}

func (x *GlobalAreaResp_GlobalArea) ProtoReflect() protoreflect.Message {
	mi := &file_site_global_area_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalAreaResp_GlobalArea.ProtoReflect.Descriptor instead.
func (*GlobalAreaResp_GlobalArea) Descriptor() ([]byte, []int) {
	return file_site_global_area_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GlobalAreaResp_GlobalArea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GlobalAreaResp_GlobalArea) GetMobileCode() string {
	if x != nil {
		return x.MobileCode
	}
	return ""
}

func (x *GlobalAreaResp_GlobalArea) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type GlobalAreaResp_GlobalLang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LanguageCode string `protobuf:"bytes,1,opt,name=languageCode,proto3" json:"languageCode,omitempty"` // 语言代码
	LanguageName string `protobuf:"bytes,2,opt,name=languageName,proto3" json:"languageName,omitempty"` // 语言名称
}

func (x *GlobalAreaResp_GlobalLang) Reset() {
	*x = GlobalAreaResp_GlobalLang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_global_area_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalAreaResp_GlobalLang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalAreaResp_GlobalLang) ProtoMessage() {}

func (x *GlobalAreaResp_GlobalLang) ProtoReflect() protoreflect.Message {
	mi := &file_site_global_area_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalAreaResp_GlobalLang.ProtoReflect.Descriptor instead.
func (*GlobalAreaResp_GlobalLang) Descriptor() ([]byte, []int) {
	return file_site_global_area_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GlobalAreaResp_GlobalLang) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *GlobalAreaResp_GlobalLang) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

var File_site_global_area_proto protoreflect.FileDescriptor

var file_site_global_area_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x61, 0x72,
	0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb6, 0x02, 0x0a, 0x0e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x34, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x1a, 0x62,
	0x0a, 0x0a, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x41, 0x72, 0x65, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x1a, 0x54, 0x0a, 0x0a, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4c, 0x61, 0x6e, 0x67,
	0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x41, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_global_area_proto_rawDescOnce sync.Once
	file_site_global_area_proto_rawDescData = file_site_global_area_proto_rawDesc
)

func file_site_global_area_proto_rawDescGZIP() []byte {
	file_site_global_area_proto_rawDescOnce.Do(func() {
		file_site_global_area_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_global_area_proto_rawDescData)
	})
	return file_site_global_area_proto_rawDescData
}

var file_site_global_area_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_site_global_area_proto_goTypes = []any{
	(*GlobalAreaResp)(nil),            // 0: proto.GlobalAreaResp
	(*GlobalAreaResp_GlobalArea)(nil), // 1: proto.GlobalAreaResp.GlobalArea
	(*GlobalAreaResp_GlobalLang)(nil), // 2: proto.GlobalAreaResp.GlobalLang
}
var file_site_global_area_proto_depIdxs = []int32{
	1, // 0: proto.GlobalAreaResp.area:type_name -> proto.GlobalAreaResp.GlobalArea
	2, // 1: proto.GlobalAreaResp.lang:type_name -> proto.GlobalAreaResp.GlobalLang
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_site_global_area_proto_init() }
func file_site_global_area_proto_init() {
	if File_site_global_area_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_site_global_area_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GlobalAreaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_global_area_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GlobalAreaResp_GlobalArea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_global_area_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GlobalAreaResp_GlobalLang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_global_area_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_site_global_area_proto_goTypes,
		DependencyIndexes: file_site_global_area_proto_depIdxs,
		MessageInfos:      file_site_global_area_proto_msgTypes,
	}.Build()
	File_site_global_area_proto = out.File
	file_site_global_area_proto_rawDesc = nil
	file_site_global_area_proto_goTypes = nil
	file_site_global_area_proto_depIdxs = nil
}
