// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: site/msg.proto

package site

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 红点响应
type RedPointResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否显示红点true是
	IsShowRedPoint bool `protobuf:"varint,1,opt,name=isShowRedPoint,proto3" json:"isShowRedPoint,omitempty"`
	// 未读消息条数
	UnreadCount int32 `protobuf:"varint,2,opt,name=unreadCount,proto3" json:"unreadCount,omitempty"`
}

func (x *RedPointResp) Reset() {
	*x = RedPointResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedPointResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedPointResp) ProtoMessage() {}

func (x *RedPointResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedPointResp.ProtoReflect.Descriptor instead.
func (*RedPointResp) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{0}
}

func (x *RedPointResp) GetIsShowRedPoint() bool {
	if x != nil {
		return x.IsShowRedPoint
	}
	return false
}

func (x *RedPointResp) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// 消息列表请求
type MsgListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息类型1-平台消息2-交易消息3-活动消息
	MsgType int32 `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	// 页码
	PageNumber int32 `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	// 页大小
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *MsgListReq) Reset() {
	*x = MsgListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgListReq) ProtoMessage() {}

func (x *MsgListReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgListReq.ProtoReflect.Descriptor instead.
func (*MsgListReq) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MsgListReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MsgListReq) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *MsgListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 消息列表项
type MsgListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 已读字段
	ReadStatus int32 `protobuf:"varint,4,opt,name=readStatus,proto3" json:"readStatus,omitempty"`
}

func (x *MsgListItem) Reset() {
	*x = MsgListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgListItem) ProtoMessage() {}

func (x *MsgListItem) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgListItem.ProtoReflect.Descriptor instead.
func (*MsgListItem) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MsgListItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgListItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MsgListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MsgListItem) GetReadStatus() int32 {
	if x != nil {
		return x.ReadStatus
	}
	return 0
}

// 消息列表响应
type MsgListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总记录数
	TotalRecord int32 `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord,omitempty"`
	// 总页数
	TotalPage int32 `protobuf:"varint,2,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	// 页面大小
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 页码
	PageNum int32 `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 平台消息列表项
	List []*MsgListItem `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *MsgListResp) Reset() {
	*x = MsgListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgListResp) ProtoMessage() {}

func (x *MsgListResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgListResp.ProtoReflect.Descriptor instead.
func (*MsgListResp) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MsgListResp) GetTotalRecord() int32 {
	if x != nil {
		return x.TotalRecord
	}
	return 0
}

func (x *MsgListResp) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *MsgListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *MsgListResp) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *MsgListResp) GetList() []*MsgListItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 交易消息标记已读请求
type MarkReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易消息Id
	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{4}
}

func (x *MarkReadReq) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 跑马灯请求
type RotatingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 跑马灯请求类型1-热门2-场馆游戏3-充值提现
	RotatingType int32 `protobuf:"varint,1,opt,name=rotatingType,proto3" json:"rotatingType,omitempty"`
}

func (x *RotatingReq) Reset() {
	*x = RotatingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotatingReq) ProtoMessage() {}

func (x *RotatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotatingReq.ProtoReflect.Descriptor instead.
func (*RotatingReq) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{5}
}

func (x *RotatingReq) GetRotatingType() int32 {
	if x != nil {
		return x.RotatingType
	}
	return 0
}

// 跑马灯项
type RotatingItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RotatingItem) Reset() {
	*x = RotatingItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotatingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotatingItem) ProtoMessage() {}

func (x *RotatingItem) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotatingItem.ProtoReflect.Descriptor instead.
func (*RotatingItem) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{6}
}

func (x *RotatingItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RotatingItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 跑马灯响应
type RotatingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*RotatingItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RotatingResp) Reset() {
	*x = RotatingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotatingResp) ProtoMessage() {}

func (x *RotatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotatingResp.ProtoReflect.Descriptor instead.
func (*RotatingResp) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{7}
}

func (x *RotatingResp) GetList() []*RotatingItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 消息汇总响应
type MsgSummaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 平台消息时间
	PlatformCreatedAt string `protobuf:"bytes,1,opt,name=platformCreatedAt,proto3" json:"platformCreatedAt,omitempty"`
	// 平台消息内容
	PlatformContent string `protobuf:"bytes,2,opt,name=platformContent,proto3" json:"platformContent,omitempty"`
	// 交易消息时间
	TransactionCreatedAt string `protobuf:"bytes,3,opt,name=transactionCreatedAt,proto3" json:"transactionCreatedAt,omitempty"`
	// 交易消息内容
	TransactionContent string `protobuf:"bytes,4,opt,name=transactionContent,proto3" json:"transactionContent,omitempty"`
	// 交易消息未读数量
	TransactionUnreadCount int32 `protobuf:"varint,5,opt,name=transactionUnreadCount,proto3" json:"transactionUnreadCount,omitempty"`
	// 平台消息时间
	ActivityCreatedAt string `protobuf:"bytes,6,opt,name=activityCreatedAt,proto3" json:"activityCreatedAt,omitempty"`
	// 平台消息内容
	ActivityContent string `protobuf:"bytes,7,opt,name=activityContent,proto3" json:"activityContent,omitempty"`
}

func (x *MsgSummaryResp) Reset() {
	*x = MsgSummaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSummaryResp) ProtoMessage() {}

func (x *MsgSummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSummaryResp.ProtoReflect.Descriptor instead.
func (*MsgSummaryResp) Descriptor() ([]byte, []int) {
	return file_site_msg_proto_rawDescGZIP(), []int{8}
}

func (x *MsgSummaryResp) GetPlatformCreatedAt() string {
	if x != nil {
		return x.PlatformCreatedAt
	}
	return ""
}

func (x *MsgSummaryResp) GetPlatformContent() string {
	if x != nil {
		return x.PlatformContent
	}
	return ""
}

func (x *MsgSummaryResp) GetTransactionCreatedAt() string {
	if x != nil {
		return x.TransactionCreatedAt
	}
	return ""
}

func (x *MsgSummaryResp) GetTransactionContent() string {
	if x != nil {
		return x.TransactionContent
	}
	return ""
}

func (x *MsgSummaryResp) GetTransactionUnreadCount() int32 {
	if x != nil {
		return x.TransactionUnreadCount
	}
	return 0
}

func (x *MsgSummaryResp) GetActivityCreatedAt() string {
	if x != nil {
		return x.ActivityCreatedAt
	}
	return ""
}

func (x *MsgSummaryResp) GetActivityContent() string {
	if x != nil {
		return x.ActivityContent
	}
	return ""
}

var File_site_msg_proto protoreflect.FileDescriptor

var file_site_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0c, 0x52, 0x65, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x73, 0x53, 0x68, 0x6f,
	0x77, 0x52, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x62, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x75, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xab, 0x01, 0x0a,
	0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65,
	0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e,
	0x75, 0x6d, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x4d, 0x61,
	0x72, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x31, 0x0a, 0x0b, 0x52,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x32,
	0x0a, 0x0c, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0c, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xdc, 0x02, 0x0a, 0x0e,
	0x4d, 0x73, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c,
	0x0a, 0x11, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_site_msg_proto_rawDescOnce sync.Once
	file_site_msg_proto_rawDescData = file_site_msg_proto_rawDesc
)

func file_site_msg_proto_rawDescGZIP() []byte {
	file_site_msg_proto_rawDescOnce.Do(func() {
		file_site_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_msg_proto_rawDescData)
	})
	return file_site_msg_proto_rawDescData
}

var file_site_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_site_msg_proto_goTypes = []any{
	(*RedPointResp)(nil),   // 0: proto.RedPointResp
	(*MsgListReq)(nil),     // 1: proto.MsgListReq
	(*MsgListItem)(nil),    // 2: proto.MsgListItem
	(*MsgListResp)(nil),    // 3: proto.MsgListResp
	(*MarkReadReq)(nil),    // 4: proto.MarkReadReq
	(*RotatingReq)(nil),    // 5: proto.RotatingReq
	(*RotatingItem)(nil),   // 6: proto.RotatingItem
	(*RotatingResp)(nil),   // 7: proto.RotatingResp
	(*MsgSummaryResp)(nil), // 8: proto.MsgSummaryResp
}
var file_site_msg_proto_depIdxs = []int32{
	2, // 0: proto.MsgListResp.list:type_name -> proto.MsgListItem
	6, // 1: proto.RotatingResp.list:type_name -> proto.RotatingItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_site_msg_proto_init() }
func file_site_msg_proto_init() {
	if File_site_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_site_msg_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RedPointResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MsgListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MsgListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MsgListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MarkReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RotatingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RotatingItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RotatingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_msg_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*MsgSummaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_site_msg_proto_goTypes,
		DependencyIndexes: file_site_msg_proto_depIdxs,
		MessageInfos:      file_site_msg_proto_msgTypes,
	}.Build()
	File_site_msg_proto = out.File
	file_site_msg_proto_rawDesc = nil
	file_site_msg_proto_goTypes = nil
	file_site_msg_proto_depIdxs = nil
}
