// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: site/security.proto

package site

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 认证信息响应
type SecurityAuthInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode string `protobuf:"bytes,1,opt,name=areaCode,proto3" json:"areaCode,omitempty"` // 地区编码
	Mobile   string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`     // 手机号
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱
}

func (x *SecurityAuthInfoResp) Reset() {
	*x = SecurityAuthInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_security_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityAuthInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityAuthInfoResp) ProtoMessage() {}

func (x *SecurityAuthInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_site_security_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityAuthInfoResp.ProtoReflect.Descriptor instead.
func (*SecurityAuthInfoResp) Descriptor() ([]byte, []int) {
	return file_site_security_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityAuthInfoResp) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *SecurityAuthInfoResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SecurityAuthInfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 绑定请求信息
type SecurityBindingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountType int32  `protobuf:"varint,1,opt,name=accountType,proto3" json:"accountType,omitempty"` // 账号类型 1-手机 2-邮箱
	AreaCode    string `protobuf:"bytes,2,opt,name=areaCode,proto3" json:"areaCode,omitempty"`        // 地区编码
	Mobile      string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`            // 手机号
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`              // 邮箱
	Code        string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`                // 验证码
}

func (x *SecurityBindingReq) Reset() {
	*x = SecurityBindingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_security_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityBindingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityBindingReq) ProtoMessage() {}

func (x *SecurityBindingReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_security_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityBindingReq.ProtoReflect.Descriptor instead.
func (*SecurityBindingReq) Descriptor() ([]byte, []int) {
	return file_site_security_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityBindingReq) GetAccountType() int32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

func (x *SecurityBindingReq) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *SecurityBindingReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SecurityBindingReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SecurityBindingReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_site_security_proto protoreflect.FileDescriptor

var file_site_security_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x14,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x94,
	0x01, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x42, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_security_proto_rawDescOnce sync.Once
	file_site_security_proto_rawDescData = file_site_security_proto_rawDesc
)

func file_site_security_proto_rawDescGZIP() []byte {
	file_site_security_proto_rawDescOnce.Do(func() {
		file_site_security_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_security_proto_rawDescData)
	})
	return file_site_security_proto_rawDescData
}

var file_site_security_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_site_security_proto_goTypes = []any{
	(*SecurityAuthInfoResp)(nil), // 0: proto.SecurityAuthInfoResp
	(*SecurityBindingReq)(nil),   // 1: proto.SecurityBindingReq
}
var file_site_security_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_site_security_proto_init() }
func file_site_security_proto_init() {
	if File_site_security_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_site_security_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SecurityAuthInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_security_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SecurityBindingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_security_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_site_security_proto_goTypes,
		DependencyIndexes: file_site_security_proto_depIdxs,
		MessageInfos:      file_site_security_proto_msgTypes,
	}.Build()
	File_site_security_proto = out.File
	file_site_security_proto_rawDesc = nil
	file_site_security_proto_goTypes = nil
	file_site_security_proto_depIdxs = nil
}
